# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "138ef9418d0be545a3a246a0dfc4b365"
name = "Shoppable Blog & SEO"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_files,read_products,read_themes,write_app_proxy,write_content,write_files"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/auth/callback" ]

[app_proxy]
url = "https://shopify.dev/apps/default-app-home/api"
subpath = "shoppable-blog-seo"
prefix = "apps"
