# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "138ef9418d0be545a3a246a0dfc4b365"
name = "RankAI SEO Audit & Optimizer"
handle = "rankai-seo-audit-optimizer"
application_url = "https://shopable-blog.bluepeaks.top"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_files,read_inventory,read_products,read_themes,write_app_proxy,write_content,write_files,write_pixels,write_products,read_customer_events"

[auth]
redirect_urls = [
  "https://shopable-blog.bluepeaks.top/auth/callback",
  "https://shopable-blog.bluepeaks.top/auth/shopify/callback",
  "https://shopable-blog.bluepeaks.top/api/auth/callback"
]

[app_proxy]
url = "https://shopable-blog.bluepeaks.top/api"
subpath = "shoppable-blog-seo"
prefix = "apps"

[webhooks.privacy_compliance]
customer_deletion_url = "https://shopable-blog.bluepeaks.top/webhooks/customers/redact"
customer_data_request_url = "https://shopable-blog.bluepeaks.top/webhooks/customers/data_request"
shop_deletion_url = "https://shopable-blog.bluepeaks.top/webhooks/shop/redact"
