export type ChangelogRelease = {
  version: string;
  date: string;
  title: string;
  summary: string;
  tags: Array<"New" | "Improved" | "Fixed">;
  changes: Array<{ type: "New" | "Improved" | "Fixed"; text: string }>;
};

// Keep newest releases first. This is the single source used by the merchant-facing changelog.
export const CHANGELOG_RELEASES: ChangelogRelease[] = [
  {
    version: "2026.07.23",
    date: "2026-07-23",
    title: "AI content planning and optimization copilots",
    summary: "Plan, write, interlink and optimize Shopify content and images with review-first 9Router-powered AI workflows.",
    tags: ["New", "Improved", "Fixed"],
    changes: [
      { type: "New", text: "AI Image SEO scans featured and inline images across Shopify articles for missing alt text, keyword-stuffed descriptions and decorative images that should use empty alt text." },
      { type: "New", text: "Merchants can generate context-aware alt suggestions for selected images, edit each result, preview exact before-and-after values, apply up to 100 reviewed changes and undo the full batch." },
      { type: "Fixed", text: "Image SEO revalidates the article body, image index, source URL, decorative state and current alt text immediately before Apply or Undo, while preserving image files, URLs, dimensions and every non-alt HTML attribute." },
      { type: "Fixed", text: "AI Content Brief automatically retries in JSON-object mode when a routed model ignores the requested JSON schema and returns Markdown, while retaining the same server-side resource validation." },
      { type: "New", text: "AI Content Brief & Keyword Cluster builds a saved strategy, primary and secondary keyword cluster, entity coverage, H2/H3 outline, reader questions and cannibalization review from verified Shopify and Search Console data." },
      { type: "New", text: "Saved content briefs include server-verified internal-link and product-placement plans, allow each section to be regenerated, and can create a complete draft that opens prefilled in the article editor for review." },
      { type: "Fixed", text: "AI Content Brief drops invented article IDs, product IDs, URLs, queries and metrics before saving, while article drafts remain unpublished until the merchant explicitly saves them to Shopify." },
      { type: "New", text: "AI Internal Link Copilot reviews deterministic Shopify article pairs for semantic relevance, reader value and exact in-context anchor options." },
      { type: "New", text: "Internal link suggestions now support before-and-after previews, multi-select batch apply and guarded per-article Undo history." },
      { type: "Fixed", text: "AI internal links accept only server-verified Shopify article destinations, skip changed or duplicate targets, and never append an invented or unmatched anchor." },
      { type: "New", text: "AI Assistant can create or improve an SEO article from one primary keyword, optional secondary keywords and merchant instructions, including the title, body, excerpt and search metadata." },
      { type: "New", text: "Selecting a word or passage in the content editor now opens a floating Chat with AI action for improving, shortening, expanding or rewriting only that selection." },
      { type: "Improved", text: "Selected-text AI changes include a before-and-after review and replace only the approved selection in the local draft." },
      { type: "New", text: "Article titles and excerpts now include compact inline AI actions that match the content editor controls." },
      { type: "Improved", text: "SEO issue fixes are available beside their corresponding SEO score findings instead of requiring a separate issue list." },
      { type: "Improved", text: "Long-paragraph fixes send the affected paragraphs to AI and show a reviewable proposed rewrite only after the merchant chooses Fix with AI." },
      { type: "New", text: "AI can suggest relevant external sources with titles, anchor text and context; merchants can review and select verified links before adding them." },
      { type: "Improved", text: "Content Refresh analysis runs from the current article and returns saved signals in place, without forcing merchants to leave for the Content Decay report." },
      { type: "Improved", text: "AI fixes use per-action loading states, keep other controls available and place Undo within the SEO workflow." },
      { type: "Fixed", text: "9Router responses no longer expose provider errors to merchants, and timeout or malformed-response failures return concise app guidance." },
      { type: "Fixed", text: "AI requests use non-streaming responses to prevent successful provider requests from appearing as empty or failed app responses." },
      { type: "Fixed", text: "AI-generated article and SEO changes preserve existing links, images, image alt text, tables and product blocks, while unsafe markup is rejected." },
      { type: "Fixed", text: "Selected-text Chat with AI now appears as a compact floating action above the selection instead of a full-width button below the editor." },
      { type: "Fixed", text: "SEO Optimizer and Catalog Manager tabs no longer reserve an empty measurement row, and Catalog Manager metric icons now stay aligned beside their values." },
      { type: "Fixed", text: "Opening a saved SEO issue for an article that was deleted in Shopify now returns to SEO Optimizer with refresh guidance instead of showing an in-app 404 page." },
      { type: "Improved", text: "The app identity is now RankAI SEO Audit & Optimizer across Shopify configuration, the theme extension, documentation, and privacy policy." },
      { type: "Fixed", text: "New installs now attempt to activate conversion tracking automatically, while Web Pixel status errors keep a visible Retry action instead of replacing the button." },
      { type: "Improved", text: "Shopify Admin and storefront app-proxy links now use the RankAI SEO Optimizer handle consistently." },
      { type: "Fixed", text: "Shopify's missing-Web-Pixel response is now treated as an inactive state so new stores proceed to pixel creation instead of stopping with a status error." },
      { type: "Fixed", text: "Dashboard setup status refreshes only once after Web Pixel activation, preventing repeated theme checks from triggering Shopify API rate limits." },
    ],
  },
  {
    version: "2026.07.22",
    date: "2026-07-22",
    title: "Catalog SEO editors and storefront performance",
    summary: "Optimize Shopify products and collections in-app, monitor storefront speed, and retain conversion attribution across cart interactions.",
    tags: ["New", "Improved", "Fixed"],
    changes: [
      { type: "New", text: "AI Content Refresh Copilot turns saved Content Decay findings and real Search Console queries into a selective, review-only article refresh with before-and-after previews and undo." },
      { type: "Improved", text: "Content refreshes preserve article links, images, tables, product blocks and TOC markers, while facts, broken links, unavailable products and outdated years remain explicit merchant verification tasks." },
      { type: "Fixed", text: "Signed conversion attribution tokens now remain valid for the same seven-day window as the Shopify Web Pixel, so delayed add-to-cart and purchase events are no longer dropped after 24 hours." },
      { type: "Fixed", text: "Web Pixel conversion requests are now awaited, kept alive through cart-drawer and navigation lifecycle changes, and retried once after transient network failures." },
      { type: "Fixed", text: "Product attribution now survives variant URL changes, with a storefront fallback for custom Shopify cart drawers that do not reliably emit the standard add-to-cart pixel event." },
      { type: "New", text: "Storefront Performance compares saved Lighthouse SEO, mobile speed and desktop speed reports for representative Shopify pages." },
      { type: "Improved", text: "Performance reports surface Core Web Vitals, Lighthouse category scores, screenshots, lab metrics, prioritized opportunities, grouped diagnostics and expandable audit details." },
      { type: "Fixed", text: "Storefront Performance scans now run in the background and update automatically instead of holding the embedded app request open until Nginx returns a 504 timeout." },
      { type: "Improved", text: "Storefront Performance keeps Homepage as the automatic target and provides one saved Other page URL selected by the merchant." },
      { type: "New", text: "SEO Optimizer now audits active Shopify products and collections alongside blog posts, with separate reports, issue summaries, filters and pagination." },
      { type: "Fixed", text: "Product and collection SEO reports use Shopify-native pagination and redirect invalid page numbers to the last available page." },
      { type: "Improved", text: "Product and collection SEO now includes detailed in-app editors for storefront content, search listings, URL handles, image alt text, focus keywords and internal-link guidance." },
      { type: "Improved", text: "Catalog editors include rich-text editing, live search previews, grouped SEO checks, resource details and an unsaved-changes save bar." },
      { type: "Fixed", text: "Catalog rich-text editing preserves the caret, renders headings visually, edits or removes links without navigating, and supports collapsible issue groups." },
      { type: "Improved", text: "Product and collection scoring covers search appearance, content depth and structure, readability, contextual links, keyword placement and Shopify image checks." },
      { type: "Fixed", text: "Catalog card icons stay aligned, collection saves use the Shopify Admin API 2026-04 mutation format, and concise GraphQL errors replace raw response dumps." },
      { type: "Improved", text: "Successful catalog saves now use a compact Polaris toast inside the editor." },
      { type: "Fixed", text: "Product and Collection list scores refresh from the same live audit used by the editor, preventing stale score differences after scoring rules change." },
      { type: "Improved", text: "Removed the redundant Product or Collection badge beside the catalog editor title." },
      { type: "New", text: "Catalog Manager provides a dedicated searchable and filterable workspace for managing Shopify products and collections, separate from SEO issue triage." },
      { type: "Improved", text: "Product and Collection tabs in SEO Optimizer now group findings by issue, impact, effort and suggested fix, with affected resources available for review and editing." },
      { type: "Improved", text: "Catalog review dialogs now open the full in-app Product or Collection editor instead of sending merchants to the Shopify admin editor." },
      { type: "Fixed", text: "SEO scope tabs now use equal vertical padding and consistent control height in both SEO Optimizer and Catalog Manager." },
      { type: "Fixed", text: "The catalog rich-text style selector now preserves the text selection, applies Paragraph, Heading and Quote blocks reliably, and follows the block under the cursor." },
    ],
  },
  {
    version: "2026.07.21",
    date: "2026-07-21",
    title: "Faster SEO Optimizer and incremental scans",
    summary: "SEO reports now open from a lightweight saved snapshot while fresh Shopify scans run only when requested.",
    tags: ["Improved", "Fixed"],
    changes: [
      { type: "Improved", text: "SEO Optimizer no longer downloads and re-audits every article when the report page opens." },
      { type: "Improved", text: "SEO scans use cursor pagination and cover stores with more than 100 articles per blog." },
      { type: "Improved", text: "Content hashes skip detailed audits for unchanged articles while preserving portfolio-wide checks." },
      { type: "Improved", text: "Search Console insights load bounded opportunity rows and database aggregates instead of every query row." },
      { type: "Improved", text: "A lightweight CSS issue chart replaces the larger chart dependency on SEO Optimizer." },
      { type: "Fixed", text: "Internal-link lookup and related-post scoring scale more efficiently for large blog libraries." },
      { type: "Improved", text: "Dashboard and Analytics now reuse the saved article snapshot instead of downloading the same Shopify article list again." },
      { type: "Improved", text: "Dashboard event metrics are aggregated by day in PostgreSQL before they reach the application." },
      { type: "Improved", text: "Theme and Web Pixel status checks load after the Dashboard renders and no longer create resources during a page view." },
      { type: "Improved", text: "Analytics now reads daily aggregates and unique-session counters instead of loading every raw tracking event." },
      { type: "Improved", text: "Existing tracking history is backfilled automatically, while new events update raw and aggregate data in one idempotent transaction." },
      { type: "New", text: "A configurable raw-event retention command keeps long-term daily reports while controlling database growth." },
      { type: "New", text: "SEO scans now run in a persistent background queue with live progress, cancellation, failure recovery and optional weekly scheduling." },
      { type: "New", text: "Internal Linking Assistant suggests related articles and natural anchors, detects orphan and broken links, maps topic clusters, and inserts links only after approval." },
      { type: "Improved", text: "Internal Linking reports are saved per shop and organized into overview, suggestions, issues and topic cluster tabs." },
      { type: "Improved", text: "Merchants can leave SEO Optimizer while a scan runs, avoiding long browser requests and timeouts on large stores." },
      { type: "Fixed", text: "Uninstall and privacy cleanup now includes analytics aggregates, Search Console records, bulk-change history and SEO scan jobs." },
      { type: "Fixed", text: "Dashboard setup can activate a missing Shopify Web Pixel again without creating resources during page load." },
      { type: "Fixed", text: "Analytics session comparison now groups date ranges correctly on PostgreSQL." },
      { type: "Fixed", text: "Web Pixel and bulk SEO mutations now send valid GraphQL documents to Shopify." },
      { type: "Fixed", text: "Deferred setup checks show a neutral checking state instead of flashing an error before completion." },
      { type: "Fixed", text: "Weekly scan and scan-result notifications are shown only once per action or job." },
      { type: "Fixed", text: "The SEO worker uses the app's explicit localhost endpoint and reports invalid internal responses clearly." },
      { type: "Fixed", text: "Background scans call the Remix data action directly instead of receiving a rendered HTML document." },
      { type: "Fixed", text: "SEO scan failures show merchant-safe guidance while technical details remain in server logs." },
      { type: "Improved", text: "SEO scan progress now advances per Shopify page, article-analysis batch and saved-result batch." },
      { type: "New", text: "Content quality and E-E-A-T checks now review actionable Shopify article signals: authorship, citations, first-hand experience and direct answers." },
      { type: "Improved", text: "Checks without a reliable Shopify field or an in-app fix are omitted instead of appearing as errors merchants cannot resolve." },
      { type: "New", text: "Duplicate and cannibalization audits now detect duplicate Shopify article titles and overlapping search intent even when focus keywords differ." },
      { type: "Improved", text: "Near-duplicate content checks now scale to large Shopify blog libraries instead of stopping at 300 posts." },
      { type: "Improved", text: "Cannibalization guidance recommends Shopify-compatible actions: consolidate content, separate focus topics, update internal links and create URL redirects." },
      { type: "New", text: "Advanced Image SEO detects missing dimensions, over-optimized alt text, decorative-image alt misuse, small images and image sources that search engines cannot crawl." },
      { type: "Improved", text: "Image guidance is Shopify-aware: it recommends Shopify-hosted CDN images without forcing formats or theme-level LCP changes that the article editor cannot safely fix." },
      { type: "Fixed", text: "Choosing an image size in the article editor now saves matching width and height attributes from the image aspect ratio, resolving missing-dimension SEO warnings." },
      { type: "Improved", text: "Resolved article checks remain visible as green passed items, with image checks grouped in a dedicated Image SEO section instead of disappearing after a fix." },
      { type: "Fixed", text: "SEO scores now reflect resolved image and content issues even before a focus keyword is configured, while still reserving points for keyword analysis." },
      { type: "Fixed", text: "Images reset to Original size no longer reopen as a 600px preset when their intrinsic width happens to be 600 pixels." },
      { type: "New", text: "Content Decay Monitor identifies declining organic clicks and CTR, stale articles, outdated title years, unavailable Shopify products and broken outbound links in a saved per-shop report." },
      { type: "Improved", text: "Content decay checks use Shopify product inventory policies and Search Console comparison periods, while keeping all article changes review-only." },
      { type: "Fixed", text: "Content Decay falls back to Shopify product status when an installed shop has not granted inventory access, instead of failing the full analysis." },
      { type: "Improved", text: "The app now requests read-only Shopify inventory access so Content Decay can distinguish genuinely out-of-stock products while respecting continue-selling policies." },
      { type: "Fixed", text: "Content Decay Shopify queries now use valid GraphQL document formatting instead of failing with an unexpected end-of-file parser error." },
      { type: "Fixed", text: "Long tracked outbound URLs in Content Decay are compacted with tooltips and can no longer stretch or break the report table layout." },
      { type: "Improved", text: "Content Decay table columns now prioritize article titles, URLs and recommended actions while keeping priority and action controls compact." },
      { type: "Improved", text: "Content Decay issues are paginated in 20-row pages with filter-aware Previous and Next controls." },
      { type: "Improved", text: "Content Decay Monitor is now reserved for the Growth plan, with server-side enforcement and a clear upgrade path for other plans." },
      { type: "Improved", text: "Settings now shows only Shopify-connected controls, removing placeholder SEO, AI, analytics and destructive actions that did not affect the store." },
      { type: "Fixed", text: "Settings validates saved values, reports save failures, warns before closing a page with unsaved changes and uses responsive controls on smaller admin screens." },
      { type: "Improved", text: "Legacy display and content-navigation settings URLs now redirect to the single canonical Settings workspace." },
      { type: "Improved", text: "Internal Linking Assistant is now available on Pro and Growth plans, with server-side access enforcement and an upgrade path for Free stores." },
      { type: "Fixed", text: "Shoppable display image ratios now resize only the product image area in both Live preview and the storefront widget, without treating the entire product card as the ratio target." },
    ],
  },
  {
    version: "2026.07.20",
    date: "2026-07-20",
    title: "Bulk SEO fixes with safe preview and undo",
    summary: "Review and apply search metadata and image accessibility improvements across multiple blog posts.",
    tags: ["New", "Improved"],
    changes: [
      { type: "New", text: "Bulk SEO Fix for SEO titles and meta descriptions, with an explicit before/after preview." },
      { type: "New", text: "Featured-image alt text suggestions that preserve existing alt text and can be edited before publishing." },
      { type: "New", text: "Per-shop change history and Undo for metadata and featured-image alt text." },
      { type: "Improved", text: "SEO Optimizer can send all posts affected by selected issues directly to Bulk SEO Fix." },
      { type: "Improved", text: "Suggestions fill missing metadata without overwriting good values that already exist." },
    ],
  },
  {
    version: "2026.07.20-search-insights",
    date: "2026-07-20",
    title: "Deeper SEO audits and optional Search Console insights",
    summary: "More useful portfolio-level SEO checks and an optional foundation for first-party search performance data.",
    tags: ["New", "Improved", "Fixed"],
    changes: [
      { type: "New", text: "Portfolio checks for duplicate titles and descriptions, keyword cannibalization, orphan content and near-duplicate posts." },
      { type: "New", text: "Optional Google Search Console connection per shop, with 7, 28 and 90-day reporting when configured." },
      { type: "New", text: "Search opportunity detection for low CTR, striking-distance rankings, traffic decay and competing pages." },
      { type: "Improved", text: "People-first scoring no longer treats a fixed word count or focus keyword as mandatory for every article." },
      { type: "Fixed", text: "SEO image, heading, unsafe-link, author and structured-data checks now cover more real storefront issues." },
    ],
  },
  {
    version: "2026.07.20-security",
    date: "2026-07-20",
    title: "Multi-store data and tracking hardening",
    summary: "Stronger tenant boundaries and safer attribution for stores using the app.",
    tags: ["Improved", "Fixed"],
    changes: [
      { type: "Improved", text: "SEO records, article-product mappings and configuration are consistently scoped to the current shop." },
      { type: "Improved", text: "Tracking requests use signed, short-lived tokens and idempotent event keys." },
      { type: "Fixed", text: "Privacy and uninstall cleanup safely remove only the data owned by the affected shop." },
    ],
  },
  {
    version: "2026.07.03",
    date: "2026-07-03",
    title: "Support and content navigation improvements",
    summary: "Better in-app support context and more consistent navigation settings.",
    tags: ["Improved", "Fixed"],
    changes: [
      { type: "Improved", text: "In-app support can identify the current store to provide more relevant assistance." },
      { type: "Improved", text: "SEO checks recognize custom shop domains as internal links." },
      { type: "Fixed", text: "SEO scoring, table-of-contents plan checks and Shopify metadata synchronization are more consistent." },
    ],
  },
];
